name: Lint Build

on:
  pull_request:
    branches:
      - '*'

jobs:
  lint:
    name: Lint Build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 18

      - name: Install dependencies
        run: npm i

      - name: Run lint
        run: npm run lint
        
      - name: Run build
        run: npm run lint
